---
kind: pipeline
name: default

steps:
- name: build
  image: node
  pull: always
  commands:
    - yarn
    - yarn run bin
  when:
    event: tag

- name: publish
  image: plugins/github-release
  pull: always
  settings:
    api_key:
      from_secret: github
    files: bin/*
    checksum:
      - sha512
    note: CHANGELOG.md
  when:
    event: tag
---
kind: signature
hmac: 3b1f235f6a6f0ee1aa3f572d0833c4f0eec931dbe0378f31b9efa336a7462912

...
