locations:
  home:
    from: /home/myUser
    to: remote
  important:
    from: /path/to/important/stuff
    to:
      - remote
      - hdd
backends:
  remote:
    type: b2
    path: 'myBucket:backup/home'
    B2_ACCOUNT_ID: account_id
    B2_ACCOUNT_KEY: account_key
  hdd:
    type: local
    path: /mnt/my_external_storage